### ISSUE TITLE
ORM搞个单独的出来?

### ISSUE THREAD

**Issue by clms2** [AxiosCros/tpr-db#1]
可以把ORM独立出来吗？模型、模型关系什么的很好用

**Comment by AxiosLeo** [comment]
@clms2 
我这版是去掉Model模型的，只有Db类的保留下来的。
如果要使用thinkphp的Model模型的话，建议使用topthink/think-orm

我是因为在自己的项目中完全不使用Model模型了，才把Db类独立出来的。
原因主要是因为：
1. 我需要在一个接口请求中连接多个数据库，并且要求读写分离。tp的orm针对一个数据库的操作还是不错的，但是数据库一多的话，操作和配置起来就有些麻烦了，不太好维护。

2.Model模型的性能不是很好，消耗的资源稍微多一些，尤其是同一进程，不断重复查询，不过这个tp官方的orm做了查询缓存，可以略微解决这个问题。但是这个缓存的功能跟tp框架有点耦合，不太适合移植到其它框架。

3.基于Db类，我做了多数据库连接器的机制，挺方便的，独立出来后就可以在别的框架中使用了，比如phalcon。

4.另外一个小原因就是，tp官方的代码好多warning，也有一些bug，看着难受就自己重构了。。。
